// packages/create-bubbles/template-vp-monorepo-react-nestjs/packages/i18n/react/src/use-store.ts
import type { I18nState, I18nStore } from '@bubblesjs/i18n-core'
import { useMemo, useSyncExternalStore } from 'react'

/** 订阅国际化容器，并返回选择器提取的状态。 */
export function useI18nStore<T>(store: I18nStore, selector: (state: I18nState) => T): T
/** 订阅国际化容器，并返回完整状态。 */
export function useI18nStore(store: I18nStore): I18nState
/** 将外部容器订阅接入 React，根据选择器返回状态片段或完整快照。 */
export function useI18nStore<T>(
  store: I18nStore,
  selector?: (state: I18nState) => T,
): T | I18nState {
  const getSnapshot = useMemo(() => {
    let cache: { state: I18nState; value: T | I18nState } | undefined
    return () => {
      const state = store.getState()
      if (cache && Object.is(cache.state, state)) {
        return cache.value
      }
      const value = selector ? selector(state) : state
      cache = { state, value }
      return value
    }
  }, [store, selector])

  return useSyncExternalStore(store.subscribe, getSnapshot)
}

// packages/create-bubbles/template-vp-monorepo-react-hono/packages/i18n/vue/src/use-store.ts
import { computed, onScopeDispose, shallowRef } from 'vue'
import type { ComputedRef, ShallowRef } from 'vue'
import type { I18nState, I18nStore } from '@bubblesjs/i18n-core'

export function useI18nStore<T>(store: I18nStore, selector: (state: I18nState) => T): ComputedRef<T>
export function useI18nStore(store: I18nStore): ShallowRef<I18nState>
export function useI18nStore<T>(
  store: I18nStore,
  selector?: (state: I18nState) => T,
): ComputedRef<T> | ShallowRef<I18nState> {
  const state = shallowRef<I18nState>(store.getState())
  const unsubscribe = store.subscribe(() => {
    state.value = store.getState()
  })

  onScopeDispose(unsubscribe)

  return selector ? computed(() => selector(state.value)) : state
}
