// packages/create-bubbles/template-vp-monorepo-react-nestjs/apps/web/src/pages/home/index.tsx
import { createJsonStorage, i18n } from '@bubblesjs/i18n-core'
import I18nProvider, { useI18n } from '@bubblesjs/i18n-react'
import { Button } from 'antd'

const leftStore = await i18n.init({
  locale: 'zh_CN',
  loaderMessage: async (locale?: string) => (await import(`@/locales/${locale}.json`))?.default,
  storageKey: 'i18n-home-left',
  storage: createJsonStorage(localStorage),
})

const rightStore = await i18n.init({
  locale: 'en_US',
  loaderMessage: async (locale?: string) => (await import(`@/locales/${locale}.json`))?.default,
  storageKey: 'i18n-home-right',
  storage: createJsonStorage(localStorage),
})

const I18nTestNode = ({ title, switchLocale }: { title: string; switchLocale: string }) => {
  const { tr, loadLocale, locale } = useI18n()

  return (
    <section className="flex min-w-64 flex-col gap-3 rounded border border-gray-200 p-4">
      <h2 className="text-lg font-medium">{title}</h2>
      <div>{tr('保存')}</div>
      <div>{tr('你好1')}</div>
      <div>目前语言: {locale}</div>
      <Button onClick={() => void loadLocale(switchLocale)}>切换到 {switchLocale}</Button>
    </section>
  )
}

const Home = () => {
  return (
    <div className="flex min-h-screen w-full items-center justify-center gap-6 bg-white p-6">
      <I18nProvider store={leftStore}>
        <I18nTestNode title="节点 A" switchLocale="en_US" />
      </I18nProvider>

      <I18nProvider store={rightStore}>
        <I18nTestNode title="节点 B" switchLocale="zh_CN" />
      </I18nProvider>
    </div>
  )
}

export default Home

// packages/create-bubbles/template-vp-monorepo-react-nestjs/apps/web-vue/src/views/home/index.vue
<script setup lang="ts">
import { useI18n } from '@bubblesjs/i18n-vue'

const { tr, loadLocale } = useI18n()
</script>

<template>
  <div class="flex-center flex-col gap-4 h-full w-full">
    1111
    <h1 class="text-2xl font-bold">
      {{ tr('保存') }}
    </h1>
    <p class="text-gray-500">
      {{ tr('你好1') }}
    </p>

    <a class="text-white px-4 py-2 rounded-md bg-blue-500" @click="loadLocale('en_US')">
      {{ tr('English') }}
    </a>

    <a class="text-white px-4 py-2 rounded-md bg-blue-500" @click="loadLocale('zh_CN')">
      {{ tr('中文') }}
    </a>
  </div>
</template>

<style lang="scss" scoped></style>
