// packages/create-bubbles/template-vp-monorepo-react-nestjs/packages/i18n/vue/src/use-store.ts
import { onScopeDispose, shallowRef } from 'vue'
import type { I18nState, I18nStore } from '@bubblesjs/i18n-core'

/**
 * 把外部 i18n store 桥接成 Vue 响应式状态。
 * store 变化时刷新 shallowRef，组件作用域销毁时自动取消订阅。
 */
export function useI18nStore(store: I18nStore) {
  const state = shallowRef<I18nState>(store.getState())
  const unsubscribe = store.subscribe(() => {
    state.value = store.getState()
  })
  onScopeDispose(unsubscribe)
  return state
}

// packages/create-bubbles/template-vp-monorepo-react-hono/packages/i18n/react/src/use-store.ts
import { useSyncExternalStore } from 'react'
import type { I18nState, I18nStore } from '@bubblesjs/i18n-core'

export function useI18nStore<T>(store: I18nStore, selector: (state: I18nState) => T): T
export function useI18nStore(store: I18nStore): I18nState
export function useI18nStore<T>(
  store: I18nStore,
  selector?: (state: I18nState) => T,
): T | I18nState {
  if (selector) {
    return useSyncExternalStore(store.subscribe, () => selector(store.getState()))
  }
  return useSyncExternalStore(store.subscribe, store.getState)
}
